exporters:
  nop:
  otlp:
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: "${HONEYCOMB_API_KEY}"
      x-honeycomb-dataset: "sakila-metrics"
  debug:
    verbosity: detailed

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 800
    spike_limit_mib: 250
  batch: {}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
